#!/bin/sh
# chkconfig: 123456 90 10
# jupiter
#
workdir=/home/jupiter

setenv() {
    mkdir -p $workdir
    cd $workdir
    curl 
}

start() {
    cd $workdir
    /home/jupiter/jupiter.sh &
    echo "Server started."
}

stop() {
    pid=`ps -ef | grep 'jupiter' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    stop
    start
    ;;
  *)
    echo "Usage: /usr/bin/jupiter_init {start|stop|reload}"
    exit 1
esac
exit 0
